# Site settings
title: "Jason Liu"
email: "jason@jasonkliu.com"
description: "Jason Liu"
baseurl: ""
url: "http://jasonkliu.com"
twitter_username: ""
github_username:  "jasonkliu"

# Build settings
markdown: kramdown
permalink: pretty
exclude: [README.md, Gemfile, Gemfile.lock]
